name: Angular CI/CD

on:
  push:
    branches:
      - main # o el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: <tu-nombre-de-app-service>
        slot-name: <tu-nombre-de-slot> # Opcional, si estás usando slots de implementación
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
